# Name of the GitHub Action
name: Docker React CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "Master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build Docker Image
        run: docker build -t ivanclement/docker-react:1.0 -f Dockerfile.dev .

      # Runs a set of commands using the runners shell
      - name: Run Docker App
        run: |
          docker run ivanclement/docker-react:1.0 npm run test -- --coverage
